version: '3.8'

services:
  # MongoDB
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=dictionary
    networks:
      - app-network

  # Redis
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - app-network

  # Backend API
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/dictionary
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - JWT_EXPIRES_IN=7d
      - CACHE_TTL_SECONDS=86400
      - FREE_DICTIONARY_BASE=https://api.dictionaryapi.dev/api/v2/entries
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongo
      - redis
    networks:
      - app-network
    command: npm run dev

  # Frontend
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network
    command: npm start

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
