version: '3.9'

services:
  api:
    build: .
    container_name: backend-api
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
      - redis
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/dictionary_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  mongo:
    # Use versão 4.x para evitar erro AVX se seu hardware não suporta
    image: mongo:4.4
    container_name: backend-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7.0-alpine
    container_name: backend-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data:
